# password constants
PASSWORD_MIN_LENGHT: int = 4
PASSWORD_MAX_LENGHT_SLIDER: int = 64
PASSWORD_MAX_LENGHT_SPINBOX: int = 200
PASSWORD_START_VALUE: int = 12

# password strenght constants
ENTROPY_THRESHOLD: int = 45

# read_password_constants
INACTIVITY_TIMER_LENGHT: int = 120000

# mainwindow constants
MAINWINDOW_DEFAULT_GEOMETRY: tuple[int] = (100, 100, 1000, 600)
MAX_WRONG_MASTER_ATTEMPTS: int = 10


MAINWINDOW_CONSTANTS: tuple = (
    MAINWINDOW_DEFAULT_GEOMETRY,
    MAX_WRONG_MASTER_ATTEMPTS
)

UI_CONSTANTS: tuple = (
    MAINWINDOW_DEFAULT_GEOMETRY
)
PASSWORD_CONSTANTS: tuple = (
    PASSWORD_MIN_LENGHT,
    PASSWORD_MAX_LENGHT_SPINBOX,
    PASSWORD_MAX_LENGHT_SLIDER,
    PASSWORD_START_VALUE
)
